name: lego
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12=py_0
  - argh=0.26.2=py38_0
  - argon2-cffi=20.1.0=py38h294d835_2
  - astroid=2.4.2=py38_0
  - async_generator=1.10=py_0
  - atomicwrites=1.4.0=py_0
  - attrs=20.2.0=py_0
  - autopep8=1.5.4=py_0
  - babel=2.8.0=py_0
  - backcall=0.2.0=py_0
  - bcrypt=3.2.0=py38he774522_0
  - bleach=3.2.1=py_0
  - brotlipy=0.7.0=py38he774522_1000
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=py38_0
  - cffi=1.14.3=py38h7a1dbc1_0
  - chardet=3.0.4=py38_1003
  - cloudpickle=1.6.0=py_0
  - colorama=0.4.4=py_0
  - cryptography=3.1.1=py38h7a1dbc1_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - diff-match-patch=20200713=py_0
  - docutils=0.16=py38_1
  - entrypoints=0.3=py38_0
  - flake8=3.8.4=py_0
  - future=0.18.2=py38_1
  - git=2.23.0=h6bb4b03_0
  - icu=58.2=vc14hc45fdbb_0
  - idna=2.10=py_0
  - imagesize=1.2.0=py_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - intervaltree=3.1.0=py_0
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.18.1=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - isort=5.6.4=py_0
  - jedi=0.17.1=py38_0
  - jinja2=2.11.2=py_0
  - jpeg=9b=vc14h4d7706e_1
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.6.3=py38_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupytext=1.8.0=pyhd3deb0d_0
  - keyring=21.4.0=py38_1
  - lazy-object-proxy=1.4.3=py38he774522_0
  - libpng=1.6.37=h2a8f88b_0
  - libsodium=1.0.18=h62dcd97_0
  - libspatialindex=1.9.3=h33f27b4_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown-it-py=0.5.8=pyhd8ed1ab_0
  - markupsafe=1.1.1=py38he774522_0
  - mccabe=0.6.1=py38_1
  - mistune=0.8.4=py38he774522_1000
  - msys2-conda-epoch=20160418=1
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py38_0
  - nbformat=5.0.8=py_0
  - nest-asyncio=1.4.1=py_0
  - notebook=6.1.6=py38haa244fe_0
  - numpydoc=1.1.0=py_0
  - openssl=1.1.1h=he774522_0
  - packaging=20.4=py_0
  - pandoc=2.11=h9490d1a_0
  - pandocfilters=1.4.2=py38_1
  - paramiko=2.7.2=py_0
  - parso=0.7.0=py_0
  - pathtools=0.1.2=py_1
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pip=20.3.3=py38haa95532_0
  - pluggy=0.13.1=py38_0
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.8=py_0
  - psutil=5.7.2=py38he774522_0
  - pycodestyle=2.6.0=py_0
  - pycparser=2.20=py_2
  - pydocstyle=5.1.1=py_0
  - pyflakes=2.2.0=py_0
  - pygments=2.7.1=py_0
  - pylint=2.6.0=py38_0
  - pynacl=1.4.0=py38h62dcd97_1
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py38ha925a31_4
  - pyrsistent=0.17.3=py38he774522_0
  - pysocks=1.7.1=py38_0
  - python=3.8.5=h5fd99cc_1
  - python-dateutil=2.8.1=py_0
  - python-jsonrpc-server=0.4.0=py_0
  - python-language-server=0.35.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.1=py_0
  - pywin32=227=py38he774522_1
  - pywin32-ctypes=0.2.0=py38_1000
  - pywinpty=0.5.7=py38h32f6830_1
  - pyyaml=5.3.1=py38he774522_0
  - pyzmq=19.0.2=py38ha925a31_1
  - qdarkstyle=2.8.1=py_0
  - qt=5.9.7=vc14h73c81de_0
  - qtawesome=1.0.1=py_0
  - qtconsole=4.7.7=py_0
  - qtpy=1.9.0=py_0
  - requests=2.24.0=py_0
  - rope=0.18.0=py_0
  - rtree=0.9.4=py38h21ff451_1
  - send2trash=1.5.0=py_0
  - setuptools=51.0.0=py38haa95532_2
  - sip=4.19.24=py38ha925a31_0
  - six=1.15.0=py_0
  - snowballstemmer=2.0.0=py_0
  - sortedcontainers=2.2.2=py_0
  - sphinx=3.2.1=py_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - spyder=4.1.5=py38_0
  - spyder-kernels=1.9.4=py38_0
  - sqlite=3.33.0=h2a8f88b_0
  - terminado=0.9.1=py38haa244fe_1
  - testpath=0.4.4=py_0
  - toml=0.10.1=py_0
  - tornado=6.0.4=py38he774522_1
  - traitlets=5.0.5=py_0
  - ujson=4.0.1=py38ha925a31_0
  - urllib3=1.25.11=py_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - watchdog=0.10.3=py38_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py38_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py38_0
  - wincertstore=0.2=py38_0
  - winpty=0.4.3=4
  - wrapt=1.11.2=py38he774522_0
  - yaml=0.1.7=vc14h4cb57cf_1
  - yapf=0.30.0=py_0
  - zeromq=4.3.2=ha925a31_3
  - zipp=3.3.1=py_0
  - zlib=1.2.11=h62dcd97_4
  - pip:
    - gitdb==4.0.5
    - gitpython==3.1.11
    - smmap==3.0.4
prefix: C:\ProgramData\Anaconda3\envs\lego
